scripts/checkpoint.py
scripts/submit_imcalc.py
templates/im_calc_sl.template
templates/slurm_header.cfg

1.seperate write from generate sk
2.read from header and context template
3. More vars in sl template

Sl generation

---

scripts/hf_sim.py

1. --seed 0 : To automate the random number seed. The generated seed is stored in SEED file (in the same directory as output bin file) for reuse. 
2. --seed XXXXX : User specified random number seed. If SEED file is found, this specified seed is ignored.

Provide options to automate/reuse/specify random seed

---

scripts/checkpoint.py

replace csv not found with done and todo counts

replace csv not found with done and todo counts

---

scripts/cybershake/auto_submit.py
scripts/cybershake/cybershake_config.json
scripts/submit_hf.py
templates/slurm_header.cfg

commented out mem in slurm_head.cfg
added random seed option to auto_submit.py and submit_hf.py and cybershake_config.json

Random chain

---

scripts/bb_sim.py

will work if memmap works on maui

lf vs30 ref taken from VM by default

---

estimation/estimate_cybershake.py

Sources dir being checked for realisations rather than Runs dir.

Fix for bug in estimation.

---

.gitignore
scripts/cybershake/install_cybershake.py

Auto_install:
``` 
Runs
| 
Albury        root_params.yaml
|
Albury_HYP15-21_S1384        fault_params.yaml
|
sim_params.yaml
```
Manual install:
root/fault/sim_params.yaml all inside Albury_HYP15-21_S1384

fault&root yaml location fix

---

estimation/estimate_cybershake.py

Added check to ignore directories that aren't realisations.

Minor estimation fix

---

scripts/test_emod3d.sh

Changed to check Rlog for line about writing seis and xyts files, and only check for the files if the line is there

Test emod3d extend

---

templates/post_emod3d_merge_ts.sl.template

Tar all files at the end of the job.

If the files have been tared already then untar them.

---

scripts/bbbatch2shrink.py

script can find all BB bin files and make them only include less stations and compress them all with flac

batch process BB files

---

.travis.yml
dashboard/DashboardDB.py
dashboard/run_dashboard_app.py
dashboard/run_data_collection.py
testing/test_common_set_up.py
testing/test_dashboard/test_DashboardDB.py

use sreport for getting daily and total core hours usage

Sreport chours

---

dashboard/run_dashboard_app.py

1.Added available inodes line to plot
2.No previous/next button below squeue table

Tidy up maui dash

---

scripts/cybershake/queue_monitor.py

Files are only removed if they have successfully been converted to

---

shared_workflow/shared.py

datetime is already imported with

---

install_workflow/README.md
install_workflow/create_env.sh
install_workflow/env_config.json
install_workflow/mahuika_python2_requirements.txt
install_workflow/mahuika_python3_requirements.txt
install_workflow/maui_python2_requirements.txt
install_workflow/maui_python3_requirements.txt

- Updated README
- Removed unneeded code for copy of estimation models (as these are now in git)
- Removed qcore from requirements (as this was error, and installed from the cloned version anyways)

Minor environments update:

---

CHANGELOG.md
scripts/cybershake/install_cybershake_fault.py

extents are checked against the bounds of the VM

Validate VM is now given the first srf found, which means that the srf

---

e2e_tests/E2ETests.py
scripts/cybershake/auto_submit.py
scripts/management/MgmtDB.py

Relies on https://github.com/ucgmsim/slurm_gm_workflow/pull/180

Only run needed rels

---

scripts/cybershake/auto_submit.py

(expecting 0, but default was set to None)

a quick fix to enable auto_submit to work for HF if seed is not provided

---

scripts/cybershake/auto_submit.py
shared_workflow/workflow_logger.py

being open at the same time
Slight logging related refactor for autosubmit

Added clean up for task related loggers to prevent too many file handles

---

dashboard/cybershake_progress.py
estimation/estimate_cybershake.py
estimation/model.py

Cybershake progress fix

---

scripts/cybershake/auto_submit.py
scripts/cybershake/install_cybershake.py
scripts/cybershake/install_cybershake_fault.py
scripts/hf_sim.py
scripts/submit_hf.py
shared_workflow/install_shared.py

This value is used as the default in all locations where the hf seed is passed

HF seed now has a default value set in constants

---

dashboard/run_dashboard_app.py

1. Added datepicker for custom date selection
2. Updated all callbacks. Now when dropdown is selected, the droodown value will be passed into datepicker, and then datepicker will update the graphs and texts.

Datepicker

---

scripts/bb_sim.py
scripts/hf_sim.py

Add and update logging messages for HF/BB so that processor wait times

---

scripts/management/MgmtDB.py

limit are given a new task instance only if they don't already have one
partially completed
Fixed sql

Changed surrounding logic so that only tasks with less failures than the

---

CHANGELOG.md
README.md
scripts/set_runparams.py
scripts/submit_emod3d.py
templates/gmsim/16.1/emod3d_defaults.yaml
templates/gmsim/18.5.3.4/emod3d_defaults.yaml

Stopped EMOD3D doing partial result dumps as it resulted in restart errors
Updated readme and changelog
Did catch up entry for changelog
- Have you updated the README yes
- Have you updated the CHANGELOG yes

Checkpoint changes

---

CHANGELOG.md
dashboard/DashboardDB.py
dashboard/run_dashboard_app.py
dashboard/run_data_collection.py
dashboard/run_old_data_collection.py

dashboard display 0 core hours usage for long username like melody.zhu. This is because melody.zhu is collapsed into melody.z+ and stored as melody.z+ in database.

fixed 0 usage for long usernames

---

CHANGELOG.md
scripts/cybershake/auto_submit.py
scripts/im_plot.sl

1. Added im_plot & plot_stations to workflow
2. plot_ts & im_plot & plot_stations now save movie, csvs and pngs to Verification dir.
3. get .ll and model_params file from yaml
4. Changed im_plot to use 4 cpus per task
5. echo parms used to im_plot.out for debugging
6. python3 env: im_plot---> python2 env: plot_stations---->python3 env: add_to_mgmt_queue

Im plot pull

---

scripts/submit_sim_imcalc.py
templates/sim_im_calc.sl.template

updated sim_im_calc submit and template

---

scripts/im_plot.sl
scripts/plot_srf.sl
scripts/plot_ts.sl

changed visualization dir structure

---

.travis.yml
install_workflow/create_env.sh

added git clone visualiztion repo to install_workflow

Visualization setup

---

templates/gmsim/16.1/emod3d_defaults.yaml
templates/gmsim/18.5.3.4/emod3d_defaults.yaml

Enable output dumps to enable output writing at all

Re enable output dumps

---

metadata/agg_json_data.py

Some fixes for the aggregation script.

---

CHANGELOG.md
estimation/estimate_wct.py
estimation/model.py
metadata/log_metadata.py
scripts/cybershake/auto_submit.py
scripts/cybershake/install_cybershake.py
scripts/cybershake/install_cybershake_fault.py
scripts/cybershake/queue_monitor.py
scripts/cybershake/run_cybershake.py
scripts/management/MgmtDB.py
scripts/set_runparams.py
scripts/submit_bb.py
scripts/submit_emod3d.py
scripts/submit_hf.py
scripts/submit_post_emod3d.py
scripts/submit_sim_imcalc.py
shared_workflow/install_shared.py
shared_workflow/load_config.py
shared_workflow/shared.py
shared_workflow/shared_automated_workflow.py
shared_workflow/workflow_logger.py
testing/test_common_set_up.py
testing/test_scripts/test_managemnet/test_mgmt_db.py

Logging moved to qcore
- Have you updated the README no
- Have you updated the CHANGELOG yes

Refactor logging

---

CHANGELOG.md
dashboard/DashboardDB.py
dashboard/run_dashboard_app.py

dynamically get max allocation hours for the period selected from dropdown

Allocation

---

scripts/hf_sim.py

Update hf_sim.py to print argparse help

---

dashboard/run_data_collection.py
dashboard/run_old_data_collection.py

specify account name for sreport user core hours

---

metadata/log_metadata.py
shared_workflow/shared_automated_workflow.py

another squeu fix

---

CHANGELOG.md
dashboard/run_dashboard_app.py

Updated outdated dashtable attributes

Version fix

---

scripts/lf2bb.py

Allow extra arguments as passed on by auto_submit and lf2bb.sl

---

scripts/cybershake/queue_monitor.py

Assumes script run machine if not present.

Added logic to check the correct machine.

---

scripts/cybershake/install_cybershake_fault.py

Add check to make sure flo in the vm_params and root_params match

---

CHANGELOG.md
scripts/bb_sim.py
scripts/cybershake/install_cybershake_fault.py
scripts/set_runparams.py
shared_workflow/shared_defaults.py
templates/run_emod3d.sl.template

Added timeshifting to LF and downstream processes to account for the causality time shift
Qcore PR with the same name
- Have you updated the CHANGELOG yes?

Timeshift changes

---

install_workflow/create_env.sh

Create env update

---

CHANGELOG.md
e2e_tests/e2e_config_simple_16p1.json
e2e_tests/e2e_config_simple_18p5p3p4.json
e2e_tests/e2e_config_validation_16p1.json
e2e_tests/e2e_config_validation_18p5p3p4.json

Updated e2e tests to use data collected from the updated workflow

---

scripts/lf2bb.py

Fix spelling bug

---

e2e_tests/e2e_config_validation_18p5p3p4.json

Added and updated last validation run

---

scripts/lf2bb.py

Fix lf2bb start sec

---

scripts/empirical/agg_sim_emp_im_perms.py

Changed to take in the directory containing the empirical intensity

---

install_workflow/maui_python3_requirements.txt

Remove security vulnerability

---

shared_workflow/install_shared.py

Dup station

---

scripts/clean_up.sl

Nesi has changed their policy on pre-post

---

scripts/bb_sim.py
scripts/cybershake/install_cybershake_fault.py
scripts/hf_sim.py
scripts/submit_bb.py
scripts/submit_hf.py
shared_workflow/install_shared.py

made argparese in hf and bb to be importable

---

scripts/bb_sim.py
scripts/cybershake/install_cybershake_fault.py
scripts/submit_bb.py
templates/gmsim/20.4.1.4/root_defaults.yaml

Updates for compatibility with master across the board. And some bugfixes for new functionality.

V20p4 prerun

---

requirements.txt
scripts/cybershake/add_to_mgmt_queue.py
scripts/cybershake/queue_monitor.py
scripts/cybershake/run_cybershake.py
scripts/management/MgmtDB.py

Slack alert and hf scp

---

scripts/cybershake/run_cybershake.py

Otherwise entire slurm queue would have to be empty to change over

Make run_cybershake change pattern every iteration

---

scripts/submit_sim_imcalc.py
templates/gmsim/20.4.1.2/root_defaults.yaml
templates/gmsim/20.4.1.4/root_defaults.yaml
templates/gmsim/README.md

Tandem with https://github.com/ucgmsim/qcore/pull/183

P sa period versioning

---

scripts/cybershake/install_cybershake.py

Update station file

---

CHANGELOG.md
scripts/cybershake/run_cybershake.py

More flexibility for running tasks!!!1
- Have you updated the CHANGELOG yes?

Multi task running

---

scripts/management/MgmtDB.py

removed inconspicuous debug line

---

scripts/management/query_mgmt_db.py

Fix query_mgmt_db

---

scripts/cybershake/run_cybershake.py
scripts/schedulers/slurm.py

The run_cybershake one caused spam output to stdout
The slurm one caused a crash

Bugs bugs bugs

---

scripts/cybershake/install_cybershake.py

Log args on install

---

scripts/hf_sim.py

Bug bug bug

---

scripts/bb_sim.py
scripts/management/slurm_mgmt.db.sql

Not to be merged before https://github.com/ucgmsim/qcore/pull/195

moving the order of unknown

---

shared_workflow/gen_fd.py

Quick dirty script to generate fd files from the terminal.

gen_fd script

---

scripts/test_binary.py

binary tests for occurances of 0 in the output

---

scripts/submit_emod3d.py

force emod to always checkpoint

---

scripts/submit_empirical.py

Fix bug, gets header from the correct location now

---

scripts/schedulers/slurm.py
scripts/test_binary.py
shared_workflow/platform_configs/platform_nesi.json

Ability to submit to two different accounts for different machines.

Mahuika submit

---

scripts/test_binary.py

This seems to work. But E2Etests seem to be a bit random.

new binary test

---

scripts/hf_sim.py

If sim_bin isn't given then get path from version

Hf bin version check

---

templates/kisti_header.cfg

Change to use intel/impi

---

CHANGELOG.md
scripts/cybershake/install_cybershake.py
scripts/cybershake/install_cybershake_fault.py
shared_workflow/install_shared.py
testing/test_shared_workflow/test_install_shared.py

Two new flags were added to install_cybershake.
If both are given an error is raised.
Perturbations will be used or ignored depending on the flag given.
If neither is given but perturbation files exist an error is raised.
Minor spelling and variable name changes for clarity
Will update the run manual on the wiki as part of this
Qcore PR with the same name
- Have you updated the CHANGELOG yes

Add vm perturbations to cybershake install.

---

scripts/kisti_scripts/clean_up.pbs
scripts/kisti_scripts/hf2bb.pbs
scripts/kisti_scripts/lf2bb.pbs
templates/kisti_header.cfg

updated headers / scripts to do log n_tasks correctly

---

scripts/management/query_mgmt_db.py

Update order of db states

---

scripts/test_binary.py

test_binary prints the error catched

---

scripts/cybershake/install_cybershake.py
scripts/cybershake/install_cybershake_fault.py
shared_workflow/install_shared.py
templates/gmsim/16.1/emod3d_defaults.yaml
templates/gmsim/18.5.3.1/emod3d_defaults.yaml
templates/gmsim/18.5.3.2/emod3d_defaults.yaml
templates/gmsim/18.5.3.4/emod3d_defaults.yaml
templates/gmsim/18.5.4.1/emod3d_defaults.yaml
templates/gmsim/18.5.4.2/emod3d_defaults.yaml
templates/gmsim/18.5.4.4/emod3d_defaults.yaml
templates/gmsim/20.1.1.4/emod3d_defaults.yaml
templates/gmsim/20.1.2.4/emod3d_defaults.yaml
templates/gmsim/20.4.1.2/emod3d_defaults.yaml
templates/gmsim/20.4.1.4/emod3d_defaults.yaml
testing/test_scripts/test_set_runparams.py

Add required qpqs parameters to emod3d_defaults. These will be ignored if not used
Remove unused emod3d_defaults parameters

 Add installation logic to workflow. Similar to perturbation install logic

---

scripts/hf_sim.py

This prevents a crash when running HF

Move args default value to only be run by master

---

e2e_tests/E2ETests.py
scripts/management/MgmtDB.py
scripts/submit_sim_imcalc.py
shared_workflow/install_shared.py

Draft to merge in master easily

Fix the e2e tests by making a method to retrieve db entries with given parameters

---

templates/kisti_header.cfg

Metadata logging correctly. :face_with_head_bandage: 

---

scripts/submit_emod3d.py

Accident when refactoring during adding station orphan checking

Set auto calculate WCT to True

---

scripts/bb_sim.py

Add rounding and make correction to message

---

CHANGELOG.md
Jenkinsfile
requirements.txt

Docker image was getting old and this repo doesn't need to rely on it
- Have you updated the README no
- Have you updated the CHANGELOG :yes

Removed docker from auto testing

---

install_workflow/create_env_maui.sh

This is mostly so that when mpi4py stops working for someone I can check the source code for the solution as I keep forgetting it #Documentation

Comment explaining flag

---

scripts/submit_hf.py
shared_workflow/install_shared.py

It didn't install. Now it does.

1dvm changes/fixes

---

scripts/cybershake/install_cybershake.py
scripts/cybershake/install_cybershake_fault.py
shared_workflow/install_shared.py
testing/test_shared_workflow/test_install_shared.py

Here we go

---

shared_workflow/install_shared.py
testing/test_shared_workflow/test_install_shared.py

Oops, that's a bug

---

scripts/nesi_scripts/run_adv_im_obs_maui.sl
templates/adv_im_calc.sl.template

update the script location to reflect the newest change in IM_calc repo

update the path to match the newests script location in IM_calc repo

---

CHANGELOG.md
Jenkinsfile
e2e_tests/E2ETests.py
e2e_tests/queue_monitor_tests.py
estimation/estimate_wct.py
metadata/aggregate_hf_logs.py
requirements.txt
shared_workflow/shared.py

Tested OK - storage footprint seems ok
- Have you updated the README no
- Have you updated the CHANGELOG  yes

Added virtual env to Jenkins

---

scripts/nesi_scripts/obs_im_calc.sl

Fix path to calculate_ims

---

scripts/kisti_scripts/calc_rrups_single.pbs
scripts/kisti_scripts/hf2bb.pbs
scripts/schedulers/pbs.py

Pbs argparse

---

scripts/cybershake/auto_submit.py
scripts/cybershake/install_cybershake_fault.py
scripts/nesi_scripts/vm_gen.sl
templates/gmsim/20.4.1.2/root_defaults.yaml

Various bugs found with the pre-pro workflow.

I'm hunting rabbits

---

scripts/nesi_scripts/install_fault.sl

It doubled up variables, so everything broke

I love when code is thoroughly tested before being committed

---

scripts/im_plot.sl

Currently im_plot.sl opens a CSV file, and assumes it is "geom" component for plotting. The assumption is mostly correct as "geom" is the default component. If user wanted to include rotd50 (or any components) in the IM csv, this fix will pick up the additional component and plot it.
- Have you updated the README : No
- Have you updated the CHANGELOG : Not yet

im_plot.sl: Find all components from IM.csv and plot them

---

estimation/estimate_wct.py
scripts/cybershake/auto_submit.py
scripts/cybershake/queue_monitor.py
scripts/schedulers/abstractscheduler.py
scripts/schedulers/pbs.py
scripts/schedulers/scheduler_factory.py
scripts/schedulers/slurm.py
scripts/submit_vm_pert.py
shared_workflow/platform_config.py
shared_workflow/platform_configs/platform_kisti.json
shared_workflow/platform_configs/platform_nesi.json
shared_workflow/platform_configs/platform_tacc.json

doc for estimation numbers:
https://wiki.canterbury.ac.nz/display/QuakeCore/VM+pertbation+estimation

Vm pertb est

---

estimation/estimate_wct.py
shared_workflow/platform_configs/platform_local.json

https://wiki.canterbury.ac.nz/display/QuakeCore/IM_calc+WCT+Estimation+update

update estimate_wct to handle rotd in im_calc

---

workflow/environments/org/kisti/create_env_nurion.sh
workflow/environments/org/nesi/create_env_maui.sh

Self evident by code change / commit messages.

Enviroment creation fixes and a safeguard 

---

workflow/environments/org/nesi/create_env_maui.sh
workflow/environments/org/nesi/create_python_virtenv_mahuika.sh

create_env_common_pre.sh cd's you into the environment directory. This moves you up one level into the Environments directory, and then clones all the repos there intstead.

Remove uneeded cd

---

CHANGELOG.md
workflow/automation/execution_scripts/queue_monitor.py
workflow/automation/install_scripts/slurm_mgmt.db.sql
workflow/automation/lib/MgmtDB.py
workflow/automation/lib/schedulers/abstractscheduler.py
workflow/automation/lib/schedulers/bash.py
workflow/automation/lib/schedulers/pbs.py
workflow/automation/lib/schedulers/slurm.py

Adding new state for a job hitting wall clock time
Updated the DB and when determining retries only counts WCT states
Determines if a job hits wall clock time with pbs or slurm schedulers
- Have you updated the README (yes/no)? No
- Have you updated the CHANGELOG (yes/no)? Yes 
Was tested on Nurion, Maui and Mahuika and results all hit WCT and updated the db.

Workflow Metadata Refactor Part 1

---

workflow/automation/lib/schedulers/pbs.py
workflow/automation/org/kisti/vm_pert.pbs
workflow/automation/submit/submit_vm_pert.py
workflow/environments/org/kisti/create_env_nurion.sh
workflow/environments/org/kisti/nurion_python3_requirements.txt

Few issues with Kisti. VM_pert seems to submit now, however I may have created other issues with other scripts (let me know if you see anything that may need testing).
Otherwise, my CS run will test the workflow. :smile:

I think this fixes things.... :thinking: 

---

workflow/automation/platform_config.py

Fix bug with Kisti core count calcs

---

workflow/automation/estimation/estimate_cybershake.py
workflow/automation/estimation/estimate_wct.py
workflow/automation/execution_scripts/cybershake_progress.py
workflow/automation/metadata/collect_metadata.py

Changes to estimation and cybershake progress
No longer using json files for job duration
Optional list file for faults
Optional to specify task types
Output example (Test data)

Metadata Refactor Phase 3

---

workflow/automation/templates/post_emod3d_merge_ts.sl.template
workflow/calculation/verification/test_merge_ts.sh
workflow/calculation/verification/test_xyts.py

Merge ts pgv fix

---

workflow/automation/estimation/estimate_wct.py
workflow/automation/execution_scripts/auto_submit.py
workflow/automation/execution_scripts/cybershake_progress.py
workflow/automation/execution_scripts/query_mgmt_db.py
workflow/automation/execution_scripts/run_cybershake.py
workflow/automation/install_scripts/install_cybershake.py
workflow/automation/install_scripts/install_cybershake_fault.py
workflow/automation/lib/MgmtDB.py
workflow/automation/lib/shared_automated_workflow.py

This change depends on qcore and Pre-processing branches also going in.
Will also require an update to all users on the updated syntax, along with wiki documentation
Uploaded for comments/feedback

Median event generation

---

workflow/automation/estimation/estimate_wct.py
workflow/automation/submit/submit_sim_imcalc.py
workflow/automation/templates/adv_im_calc.sl.template

Fixes for MPI to run for IM Calc and Advanced IMs

MPI IM Calc

---

workflow/automation/estimation/estimate_cybershake.py
workflow/automation/execution_scripts/auto_submit.py
workflow/automation/lib/shared_template.py
workflow/automation/metadata/log_metadata.py
workflow/automation/submit/submit_bb.py
workflow/automation/submit/submit_emod3d.py
workflow/automation/submit/submit_empirical.py
workflow/automation/submit/submit_hf.py
workflow/automation/submit/submit_post_emod3d.py
workflow/calculation/create_e3d.py

Removed the need for DotDictify by converting each .x reference to a dictionary reference ["x"]
Reduces potential errors when x does not exisit
Was tested and works properly as expected

Removing DotDictify

---

workflow/automation/estimation/estimate_wct.py
workflow/automation/execution_scripts/auto_submit.py
workflow/automation/execution_scripts/queue_monitor.py
workflow/automation/install_scripts/install_realisation.py
workflow/automation/lib/shared.py
workflow/automation/metadata/aggregate_hf_logs.py
workflow/automation/submit/submit_bb.py
workflow/automation/submit/submit_emod3d.py
workflow/automation/submit/submit_hf.py
workflow/automation/submit/submit_post_emod3d.py
workflow/automation/submit/submit_sim_imcalc.py
workflow/automation/submit/submit_vm_pert.py
workflow/automation/tests/test_estimation/test_estimation.py
workflow/automation/tests/test_submit_scripts/test_submit_emod3d.py
workflow/automation/tests/test_submit_scripts/test_submit_hf.py
workflow/calculation/create_e3d.py
workflow/calculation/hf_sim.py
workflow/calculation/site_response_BB/site_response.py
workflow/e2e_tests/queue_monitor_tests.py

Details available here: https://wiki.canterbury.ac.nz/display/QuakeCore/Job+submission+constraints

Job submission contraints

---

workflow/automation/execution_scripts/auto_submit.py
workflow/automation/install_scripts/install_cybershake.py
workflow/automation/install_scripts/install_fault.py
workflow/automation/org/nesi/install_fault.sl
workflow/automation/templates/sim_im_calc.sl.template

Dotdictify reference

---

workflow/e2e_tests/E2ETests.py
workflow/environments/create_env_common_post.sh
workflow/environments/helper_functions/activate_common_env.sh
workflow/environments/helper_functions/activate_mahuika_python3_virtenv.sh
workflow/environments/helper_functions/activate_maui_python3_virtenv.sh
workflow/environments/load_default_modules.sh
workflow/environments/org/nesi/create_env_maui.sh
workflow/environments/org/nesi/edit_cfg.py
workflow/environments/org/nesi/update_env_to_py39.sh
workflow/environments/python_load_functions.sh

Python3.9 envs

---

workflow/automation/estimation/estimate_wct.py
workflow/automation/submit/submit_vm_pert.py

Don't scale core count for VM_pert

---

workflow/automation/execution_scripts/set_database.py

Ignore the other pull request - it was not clean against master and kept failing black test.
The .yaml file to supply looks like this:
completed:
HF:
- Lyell
- HuttPeelNorth
- CardronaN
- NorthCant13
- LkHeron
- TaieriR
- NorthBranch
- Fowlers
- Hyde
- AhuririR_REL26
- AhuririR_REL23
- AhuririR_REL19
- AhuririR_REL10

Fixed some issues with set_database.py

---

workflow/automation/estimation/estimate_wct.py
workflow/automation/execution_scripts/add_to_mgmt_queue.py
workflow/automation/execution_scripts/queue_monitor.py
workflow/automation/install_scripts/install_cybershake.py
workflow/automation/lib/shared_automated_workflow.py
workflow/automation/submit/submit_emod3d.py
workflow/automation/templates/run_hf_mpi.sl.template

Nurion2023 cs env hf fix

---

workflow/automation/org/nesi/install_fault.sl
workflow/automation/org/nesi/srf_gen.sl

Minor issues I discovered while implmenting install_fault and srf_gen for KISTI.
The instructions on how to submit the slurm script were wrong.

Minor corrections to comments

---

workflow/automation/execution_scripts/auto_submit.py

params.stat_vs_est : Wrong
params["stat_vs_est"] : Good

params[stat_vs_est] incorectly referenced

---

workflow/environments/README.md
workflow/environments/org/nesi/create_python_virtenv_mahuika.sh

Extra note to readme

---

workflow/automation/execution_scripts/auto_submit.py

os.makedirs(..,exist_ok=True) needs no checking

---

workflow/automation/estimation/estimate_cybershake.py
workflow/automation/execution_scripts/queue_monitor.py
workflow/automation/install_scripts/create_mgmt_db.py
workflow/automation/lib/MgmtDB.py
workflow/automation/lib/shared.py
workflow/automation/lib/shared_automated_workflow.py
workflow/automation/submit/submit_sim_imcalc.py
workflow/automation/submit/submit_vm_pert.py
workflow/calculation/empirical/agg_sim_emp_im_perms.py
workflow/calculation/empirical/calculate_and_aggregate_empirical_ims.py
workflow/calculation/hf2bb.py
workflow/calculation/lf2bb.py
workflow/calculation/site_response_BB/site_response.py
workflow/calculation/verification/test_lf_seis.py
workflow/e2e_tests/E2ETests.py
workflow/e2e_tests/queue_monitor_tests.py
workflow/environments/README.md
workflow/environments/org/nesi/edit_cfg.py

The steps described in this README is required to create a virtual environment on NeSI.
Found some incorrect stuffs while I walking through with Cesar and Andrew.

Revised instructions on creating an environment

---

workflow/automation/submit/submit_empirical.py
workflow/automation/templates/empirical.sl.template

This code here wants one of its argument name to be "--srfdata_ffp". In the workflow, it was left unchanged as "--srfinfo_ffp".

Argument name was updated to srfdata_ffp

---

workflow/calculation/create_e3d.py

correctly utilise simulation root argument to create3d

---

Jenkinsfile
workflow/automation/platform_config.py

Fix for the issue https://github.com/ucgmsim/slurm_gm_workflow/issues/522
Caused by https://github.com/ucgmsim/qcore/commit/97d0da316096056e093479a073793a5a4c012d8f

fix for issue #522
