ucgmsim/slurm_gm_workflow

scripts/install.py
This line was removed in https://github.com/ucgmsim/slurm_gm_workflow/pull/48/files as the dt value is not used anymore as it now comes out of the yaml params. The default constant was therefore also removed.
The line was re-added in PR https://github.com/ucgmsim/slurm_gm_workflow/pull/51/files and since the default constant is gone this currently breaks on install.
=> Bug fix for install.py

templates/gmsim/16.1/root_defaults.yaml
Default behaviour without this is lfvsref = None so it will use lfvsref values obtained from 3DVM.
This addition of lfvsref = 500.0 makes this consistent with "conventional" Graves and Pitarka (where it previously just used vsref = 500 for both LF and HF).
Have tested this on maui and seems to work.
=> added vsref to bb in root_defaults.yaml

scripts/clean_up.py, scripts/clean_up.sl
Don't nest the slurm scripts inside a folder, the top level should be
empty now that the templates are not copied over for each realisation.
=> Remove Checkpoint folder before clean up happens.

dashboard/run_dashboard_app.py, dashboard/run_data_collection.py
dashboard crash fix: ssh cmd timeout too short
red font for error text
=> extended timeout

dashboard/DashboardDB.py, dashboard/run_dashboard_app.py, dashboard/run_data_collection.py
2019-06-04 12:05:04.594923 - Collecting data from HPC [<HPC.maui: 'maui'>, <HPC.mahuika: 'mahuika'>]
The timeout of 60 expired for cmd sreport -n -t Hours cluster AccountUtilizationByUser Accounts=nesi00213 start=01/06/18-12:00:00 end=06/04/19-12:00:00.
File "run_data_collection.py", line 389, in <module>
main(args)
File "run_data_collection.py", line 358, in main
data_col.run(args.users)
File "run_data_collection.py", line 97, in run
self.collect_data(hpc, users)
File "run_data_collection.py", line 145, in collect_data
rt_total_ch = self.parse_chours_usage(rt_total_ch_output)
File "run_data_collection.py", line 268, in parse_chours_usage
return ch_lines[0].strip().split()[-2]
TypeError: 'NoneType' object is not subscriptable
=> added type error exception for none chours data & extended timeout

templates/run_bb_mpi.sl.template, templates/run_emod3d.sl.template, templates/run_hf_mpi.sl.template
Tested to work.
Places the contents of the entire BB/HF/LF folder in $nobackup/tmp/$USER/$job_id_$realisation_$job_type if the completion test fails
This means you need to use submit.sh/auto_submit.py to resubmit the task, not just sbatch the slurm script again
Has been tested
=> Backup failed binaries

install_workflow/create_env.sh, install_workflow/create_python_virtenv_mahuika.sh, install_workflow/mahuika_python3_requirements.txt
When installing environment on hpc, instead of deploying qcore/Im_calc/emprical_enigne etc into site packages, deploy their git version so that code is up-to-date without keeping 2 copies
eg. import qcore
qcore.__file__  == /nesi/project/nesi00213/Environments/melody/qcore/qcore/_init__.py
=> changed pip install to dev mode; added Cython to mahuika requirements

CHANGELOG.md, scripts/submit_sim_imcalc.py, templates/sim_im_calc.sl.template
fixed im_calc completion check.
The reason that im_calc is shown "completed" in mgmt_db even there's runtime error is due to the missing of "not" in im_calc template when checking output file existence.
=> fix im_calc compeletion check

CHANGELOG.md, scripts/calc_rrups_single.sl, scripts/clean_up.sl, scripts/cybershake/add_to_mgmt_queue.py, scripts/cybershake/auto_submit.py, scripts/cybershake/queue_monitor.py, scripts/cybershake/run_cybershake.py, scripts/hf2bb.sl, scripts/im_plot.sl, scripts/lf2bb.sl, scripts/management/MgmtDB.py, scripts/plot_srf.sl, scripts/plot_ts.sl, shared_workflow/shared_automated_workflow.py, templates/post_emod3d_merge_ts.sl.template, templates/run_bb_mpi.sl.template, templates/run_emod3d.sl.template, templates/run_hf_mpi.sl.template, templates/sim_im_calc.sl.template
not received from squeue.
Jobs are not considered to have been cancelled/WCT killed if squeue does.
not respond correctly.
Changed add_to_mgmt_queue to take in the job id if possible to ensure the correct entry is updated.
Slurm scripts have been set to provide the job id.
If the job id is not provided the update is still applied, as each update should ony apply to one entry.
If multiple rows are modified by an update the user is alerted to this.
=> Changed get_queued_tasks to raise an exception if a valid response is

scripts/set_runparams.py
Keeping it there breaks LF runs when not using V3.0.4
=> Remove workflow config reference

templates/run_emod3d.sl.template
There was a bug found where failed runs would be considered successfully completed, even though they had failed. This attempts to prevent this bug. Bug found during other testing, solution developed there.
=> Prevent $? bug

scripts/submit_sim_imcalc.py
Changing the default component back to only geom.
And changing the default component to not be array joined twice with ' '. Aka not "-c 0 0 0 0 9 0 v e r"
=> component fixes for standard IM workflow

CHANGELOG.md, scripts/hf_sim.py
Default HF rayset is changed from 1 2 to 1, which is internally handled as [1], not [1,2] as it used to be. 
None
- Have you updated the README : No need
- Have you updated the CHANGELOG : Yes
=> Default HF rayset is changed from 1 2 to 1

CHANGELOG.md, scripts/cybershake/queue_monitor.py, scripts/management/MgmtDB.py
Reduces the chances of having two 'active' tasks for any task in a run. Only allows them to be added if they failed beforehand.
If reinstalled after some runs complete, then pre-run runs are preserved and have to be recreated manually.
=> Unique tasks

shared_workflow/install_shared.py, templates/gmsim/16.1/emod3d_defaults.yaml, templates/gmsim/18.5.3.1/emod3d_defaults.yaml, templates/gmsim/18.5.3.2/emod3d_defaults.yaml, templates/gmsim/18.5.3.4/emod3d_defaults.yaml, templates/gmsim/18.5.4.1/emod3d_defaults.yaml, templates/gmsim/18.5.4.2/emod3d_defaults.yaml, templates/gmsim/18.5.4.4/emod3d_defaults.yaml, templates/gmsim/20.1.1.4/emod3d_defaults.yaml, templates/gmsim/20.1.2.4/emod3d_defaults.yaml, templates/gmsim/20.4.1.2/emod3d_defaults.yaml, templates/gmsim/20.4.1.4/emod3d_defaults.yaml, testing/test_scripts/test_set_runparams.py
This will not affect runs without perturbations.
Correct the spelling of pertb_file to pertbfile.
The default value should never be used, but needs something there for the key to exist
=> Add pertbfile to the emod3d defaults files for all versions.

scripts/nesi_scripts/run_adv_im_obs_maui.sl, scripts/submit_sim_imcalc.py, templates/adv_im_calc.sl.template
1.updated the station matching logic so that is match both ways, this address the bug that when observed data have stations that was not included in simulation (thus failing the check_status).
2. The result of check_status is also set to flush to job_id.out so its easier to check the result, instead of logging in mgmt_db, which require more steps to check the output. the 
DB now logs the error code, instead of full message.
=> Adv im fix

scripts/hf_sim.py
The previous string format style was "%s" % var, causing var to be converted to type string and then replacing the %s in the string.
The new type using "{:s}".format(var) instead expects var to be of type string, and raises an exception when this is attempted.
Instead leaving the brackets empty allows var to be cast to string and replace the {}.
Minimum example for the issue:
"{:s}".format(0.5)
Working equivalent:
"{}".format(0.5)
=> Fix hf_sim bug

scripts/hf_sim.py, scripts/submit_hf.py
a quick bandaid fix for params == None.
it was getting parsed to "None"(string)
and causing crashes
=> quick bandaid fix for params==None

scripts/cybershake/run_cybershake.py, scripts/schedulers/abstractscheduler.py, scripts/schedulers/scheduler_factory.py, scripts/schedulers/slurm.py, scripts/submit_sim_imcalc.py, shared_workflow/platform_configs/platform_kisti.json, shared_workflow/platform_configs/platform_local.json, shared_workflow/platform_configs/platform_nesi.json, shared_workflow/platform_configs/platform_tacc.json
Checks all platform accounts for jobs before marking them as missing from queue. And a --no-queue-monitor flag if you want to run run_cs without queue-monitor thread running.
https://github.com/ucgmsim/qcore/pull/254 depends on this PR (needs to be merged at the same time)
Changes were tested in `cs_fixes` branch and then the changes applied to master.
=> cs untested account fixes etc

workflow/environments/extra_bashrc_functions.sh
Aimed at environments stuck in the past (e.g. leer2)
Ran into the inverse problem on NeSI and have added similar to the shared bashrc
=> Add old style environment loading

workflow/automation/lib/MgmtDB.py
- Have you updated the CHANGELOG (yes/no)? 
This adjustment is in the #435 but should be merged in to ensure any jobs between now and then can work if they hit WCT
=> Patch killed_WCT not retrying

workflow/automation/org/nesi/calc_rrups_single.sl
```
File "/nesi/project/nesi00213/Environments/jason/workflow/workflow/automation/execution_scripts/add_to_mgmt_queue.py", line 107, in <module>
start_time=datestr_to_timestamp(args.start_time),
File "/nesi/project/nesi00213/Environments/jason/workflow/workflow/automation/execution_scripts/add_to_mgmt_queue.py", line 16, in datestr_to_timestamp
if time is not None
File "/opt/nesi/mahuika/Python/3.6.3-gimkl-2017a/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
tt, fraction = _strptime(data_string, format)
File "/opt/nesi/mahuika/Python/3.6.3-gimkl-2017a/lib/python3.6/_strptime.py", line 362, in _strptime
(data_string, format))
ValueError: time data "'2022-07-01_03:52:17'" does not match format '%Y-%m-%d_%H:%M:%S'
```
Appears to work after …
=> bug with quotes in the argument

workflow/automation/templates/nesi_header.cfg, workflow/automation/tests/test_shared_workflow/test_shared_template.py
```
JOBID PARTIT                         NAME     USER           START_TIME    STATE       TIME TIME_LIMI NODES  CPUS
2664012 nesi_r     emod3d.2013p613797_REL01   jmotha         Jul 05 00:54  RUNNING    1:47:23   4:10:00    10   800
2664102 nesi_r     emod3d.2013p543824_REL01   jmotha                  N/A  PENDING       0:00   4:30:00    13   520
```
The change below meant hyperthreading was turned on (spot the difference)
Turns out Slurm requires all header rows before any bash lines.
(sorry for the additional PR - I didn't notice this earlier)
=> removed line from header

workflow/calculation/hf_sim.py
In the newer compiled versions of hf, the dpart perturbation parameter isn't being used. Robin's currently used version of 6.0.3.9 doesn't have this feature and therefore is broken with the master version of hf_sim.py
=> changed the dpart_perturbation to only be added for version of .4

workflow/automation/execution_scripts/auto_submit.py, workflow/automation/execution_scripts/queue_monitor.py, workflow/automation/lib/MgmtDB.py, workflow/automation/submit/submit_sim_imcalc.py
Manages issue where a job can infinity be in WCT.
Now 2 different checks for max retries, check both failed and killed_WCT individually if they are less than the max retries before submitting a new job.
Added Increase WCT for IM_calc.
=> WCT retries fix

workflow/automation/estimation/estimate_wct.py, workflow/automation/tests/test_metadata/test_agg_json_data.py
est_IM_chours_single produced an error when scaling core hours as the scale_core_hours function returned np.float64 for core_hours and an array for cores.
This caused issues later down when trying to format to wct 
"{0:02.0f}:{1:02.0f}:00".format(*divmod(run_time * 60, 60))
=> Submitting IM_Calc fix

workflow/automation/submit/submit_hf.py
Setting the HF seed at the end resulted in all jobs getting the same seed value. This seed value is taken from root_params.yaml, or set to 0 if not available. This means that all realisations got the same seed, or all had a random seed, even if one was set in sim_params.yaml. This fix means that if a seed is available it will be used as it will be caught by the for loop, while realisations without an explicit seed will still use the shared/0 value as it did previously.
=> Fix HF seed bug

workflow/calculation/hf_sim.py
Previously vs values were used. 
These values are written after the binary runs, but before the output is checked. 
Now using e_dist (epicentre distance) values. 
e_dist values are read from the HF binary stderr and then written to the file after the vs value is written. 
Checking against e_dist values means that in future we can resume sites that had an issue with reading the e_dist, such as the HF binary crashing.
Currently these sites would be considered complete as the vs value has already been written before the issue is discovered.
The alternative change is to write vs values after e_dist values, but this was the smaller edit to make.
=> Change HF checkpointing

workflow/automation/estimation/estimate_wct.py, workflow/automation/tests/test_estimation/test_estimation.py
Fixing few issues that popped up when core hours are being scaled.
Includes fix for run time adjustment after core count changes when in the green zone
=> Estimation fixes due to core hour scaling

workflow/automation/estimation/estimate_wct.py, workflow/automation/submit/submit_emod3d.py, workflow/automation/tests/test_estimation/test_estimation.py
Adds estimation for the number of cores required to have sufficient memory for LF.
An investigation was taken place to find how much memory each gird point took to use as an estimate. Below is a plot that shows the distribution for memory per grid point for all of the cores for a single LF run. They tend to be somewhere between 125 and 126 bytes. To be safe a value of 150 bytes was chosen per grid point.
A minimum core count was added to the confine_wct_node_parameters function to ensure that there is that amount of cores for LF to ensure it's possible to run.
Currently running a test case on Maui to ensure it works as expected, will wait for those to pass before pushing this through to make sure it works. Also requires https://github.com/ucgmsim/qcore/pull/293 and this is why the current …
=> Estimation for LF memory

workflow/automation/templates/run_emod3d.sl.template, workflow/automation/templates/run_hf_mpi.sl.template
1. `ln -sf` ensures the symbolic link is created even if such a link already exists. This line often caused an error
2. The exit value "$?" is best assigned to a separate variable as the value gets lost when another line gets executed before the value is evaluated/checked.  Not a must in the current context, but I was debugging an HF issue with a few added lines in the script, and this "volatile" nature of $? gave me some time of confusion.
=> Minor changes to templates

workflow/automation/install_scripts/install_cybershake.py
When the user input for cybershake_root or stat_file_path are relative paths, it may run into issues.
The former was the root cause of the recent issue of HF job status not getting transitioned to Running or Completed. 
The latter results in root_params.yaml with a relative path for stat/vs30 files, and the workflow will be unable to locate these data files.
This fix enforces to obtain the full absolute path.
=> Enforces absolute path to prevent file/directory not-found-issues

workflow/automation/execution_scripts/query_mgmt_db.py
This is an intended duplicate of https://github.com/ucgmsim/slurm_gm_workflow/pull/492
After you approved the other PR, I merged master into the query_todo branch, which caused a bad merge conflict, made things quite mesy. I found it was easier to start a new branch...
-----------
query_mgmt_db.py --mode todo is supposed to give a list of jobs that still need to be done. I think it makes more sense if it shows everything that hasn't reached "completed" status.
---
Updated the query logic.
Without todo mode, you will see
...
MS04_REL29 |          EMOD3D |     failed | 13251611 |  2023-07-19 01:12:08
MS04_REL29 |          EMOD3D |     failed | 13336848 |  2023-08-08 21:40:48
MS04_REL30 |          EMOD3D |     failed | 13251613 |  2023-07-19 01:12:08
MS04_REL30 |          EMOD3D |     failed …
=> Query todo2

workflow/automation/submit/submit_emod3d.py
This branch was buried with other things unnoticed for some time.
This change allows upto 3 checkpoints per emod3d run - we noticed checkpointing is happening a bit too often.
We had an IO issue on KISTI - initially anticipated that reducing the frequency could help, hence this fix was made. 
Unfortunately, the IO issue was not completely fixed, and we had to completely turn off the checkpointing to move on. 
However, I still think it makes sense to limit the number of checkpointing to 3.
=> Limit the number of checkpoints to 3

workflow/automation/metadata/log_metadata.py
When a step in pre-processing gets executed (eg. srf_gen), some of *-params.yaml files are yet to be produced. But they are designed to be loaded in a cascade. and crash if there is one missing.
This fix will determine if the type of params.yaml should be loaded to perform a specified process type, and skip if not present.
=> Skip loading sim_/fault_/vm_params when not ready

workflow/automation/install_scripts/install_cybershake.py
To fix this error:
(python3_maui) baes@maui01: /nesi/nobackup/nesi00213/RunFolder/Validation/Methven$ python $gmsim/workflow/workflow/automation/install_scripts/install_cybershake.py . list.txt 22.2.2.1 --keep_dup_station --stat_file_path geoNet_stats+2023-06-28.ll
File "/nesi/project/nesi00213/Environments/baes/workflow/workflow/automation/install_scripts/install_cybershake.py", line 213, in <module>
main()
File "/nesi/project/nesi00213/Environments/baes/workflow/workflow/automation/install_scripts/install_cybershake.py", line 146, in main
root_params = generate_root_params(
File "/nesi/project/nesi00213/Environments/baes/workflow/workflow/automation/install_scripts/install_cybershake.py", line 180, in generate_root_params
vs30_file_path = …
=> Convert to str before replace() is called

workflow/environments/README.md, workflow/environments/org/nesi/create_python_virtenv_mahuika.sh
Noticed a few issues (or confusion) during Maui/Mahuika env creation and updated manual and scripts accordingly.
1. We need a copy of workflow somewhere (eg. home) to create a new environment. This means, sometimes you need to git clone this repo just to utilize scripts in environments directory, which will create a new environment and git clone another copy of this repo there. Maybe nice to have a separate "create_env"  repo, but it is what it is for now. 
2. When we create a new environment due to Python upgrade, things can be a little confusing
We have to make sure that the correct module of python is loaded before attempting to create a new environment.  I made it more explicit in the README
3. When a new virtual env is created, it doesn't install a new copy of pip. …
=> Update to Maui/Mahuika environment creation

workflow/automation/org/nesi/vm_pert.sl
VM Pert is meant to be executed on Mahuika and it crashes with a segmentation fault. This fixes one of the causes (the other one has been already addressed: https://github.com/ucgmsim/Pre-processing/pull/227)
This one, in particular, generaets core dumps and GDB tells it was created by validate_vm.py
Further inspection revealed that it was caused by GCC version mismatch.
(details were copied from https://uceqeng.slack.com/archives/C3SGQHXT8/p1700799356822109 and edited)
Since NeSI updated Python to 3.9,  we have to explicily load GCC/7.4.0 module to be able to run Fortran binaries (including combine_pertb as well as SRF,HF and BB calculation) in /nesi/project/nesi00213/opt/mahuika/hybrid_sim_tools 
```
module load GCC/7.4.0
```
Without loading this version of GCC, vm_pert step will crash …
=> Vm pert segfault fix

workflow/scripts/clean_up.py
When we keep the EMOD3D unchanged, but only BB calculation is different, we could copy the LF.tar produced during clean-up step to a new sim directory, and extracted it there, to re-use the LF result.
However, when a new BB calculation starts, qcore/timeseries.py will search for e3d.par and immediately exit, as that file is missing - it's never been archieved.
I'm proposing to include e3d.par to remedy this.
=> Archieve e3d.par during cleanup

workflow/automation/execution_scripts/query_mgmt_db.py, workflow/automation/lib/MgmtDB.py, workflow/automation/tests/test_scripts/test_management/test_mgmt_db.py, workflow/e2e_tests/queue_monitor_tests.py
@sarahjaneneill has been witnessing `database is locked` sqlite3.OperationalError frequently.
```
2024-02-14 02:03:11,935 - queue monitor - squeue tasks: 42576994 PD, 42576995 PD, 42576996 PD,...line 417, in get_runnable_tasks
entries = cur.execute(
sqlite3.OperationalError: database is locked
2024-02-14 02:03:27,323 - MainThread - The main auto_submit thread has terminated, and all...
```
and this is my attempt to address the issue.
Reference: https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked
I changed the code to release the connection as soon as one transaction is completed. Also gave 10 secs timeout before screaming "database is locked".
Tested by Sarah, and myself - the issue is not happening while burning half million core hours.
=> Fixing "Database is locked" issue

workflow/automation/templates/sim_im_calc.sl.template
This must have been around sometime, but only noticed today.
`load_sim_params()` returns a dictionary, and we no longer support the dictionary values accessed like an object attribute.
`params.FD_STATLIST` causes this:
```
>>> params.FD_STATLIST
File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'FD_STATLIST'
```
=> params.FD_STATLIST->params['FD_STATLIST']

workflow/automation/templates/run_emod3d.sl.template
When EMOD3D fails, the slurm/PBS script relocate incomplete output files to a temporary directory for later debug.
However, it also moves e3d.par, which will make the restart attempt futile as it will fail instantly if e3d.par is missing.
This change hopefully fixes this issue
=> Skip e3d.par when moving tmp files

workflow/environments/README.md
NeSI is planning to retire old modules based on gimkl/2017a toolchain, meaning Python 3.9 is on its way out, and we have Python 3.11. Sadly we are still stuck at Python 3.9 on Maui.
I created a new Python 3.11-based Mahuika environment, but made an easy option to roll back to Python 3.9-based environment.
For new 3.11-based environment, your .bashrc should have
```bash
MAUI_PYTHON_VER=3.9
MAHUIKA_PYTHON_VER=3.11
source /nesi/project/nesi00213/share/bashrc.uceq.gcc123
```
To go back to old 3.9-based env, 
```bash
MAUI_PYTHON_VER=3.9
MAHUIKA_PYTHON_VER=3.9
source /nesi/project/nesi00213/share/bashrc.uceq.gcc123
```
OR 
```bash
PYTHON_VER=3.9
source /nesi/project/nesi00213/share/bashrc.uceq
```
The second option is what everyone is expected to have in the .bashrc currently.
If .bashrc …
=> Updated README for environment setup to use Python 3.11 on Mahuika

workflow/automation/lib/MgmtDB.py
Issue ##519
@lispandfound made some interesting comments in the issue page, but I propose to move forward with this fix - I held off making this PR until we produce a better engineered solution, and temporarily applied a patch to each user's env as it takes so many hours just to complete install_cybershake.py for something that shouldn't take more than a few seconds.
I reached a point where It becomes a little messy to manage multiple users and multiple environments without this little fix.
Can we just merge this and move on?
=> Fix for terribly slow install_cybershake.py

workflow/automation/lib/MgmtDB.py
This morning,  I noticed NeSI file system was very slow - it took like 20 seconds to get "ls" output. 
SLURM was also terribly slow.  It took quite a while to get the `squeue` output. 
Coincidentally and interestingly, I had a few instances of run_cybershake running. All of them stopped, complaining "database is locked". 
We have been revisiting this many times, without fully understanding the root cause - I am convinced that it is just the unfortunate drop of IO speed, making sqlite3 believe the DB is locked as if there are other threads blocking its access. There aren't.
We run our workflow on NeSI login node that typically have many people connect to and occasionally abuse. 
It could be longer, but 50 seconds of timeout should be reasonable.
=> Revisit to the *DB is locked* issue

workflow/automation/org/nesi/srf_gen.sl
We always use 1 core for SRF_GEN, but incorrectly (and wastefully) requested 32!!
Also note that this job is meant to be submitted to mahuika, and it is submitted without `--export=ALL` option.
This is correct as we may be submitting the job from Maui, and we don't want to enforce its environment to Mahuika.
However, when a Mahuika compute node receives this job, it doesn't know which environment it is supposed to use.
Previously we had an IF block and only activated the environment when the job was submitted from Maui. 
Removal of this IF block will ensure the job can be submitted from any machine, and the correct Python environment is used.
=> Use 1 core for SRF_GEN

workflow/automation/org/nesi/install_realisation.sl
@capajaro had a case where INSTALL_REALISATION step correctly produces `sim_params.yaml`, but constantly marked as `failed`.
I noticed that his event name had too many underscores. One of his median events (his events have no other realisations), for example, is `3366146_Atzori_et_al_2012_Multi` 
When a job is submitted, 
```
sbatch  --export=CUR_ENV,CUR_HPC -M mahuika  /scale_wlg_persistent/filesets/project/nesi00213/Environments/cesar/workflow/workflow/automation/org/nesi/install_realisation.sl 3366146_Atzori_et_al_2012_Multi /scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/cpa148/200m_Sel_Event_Specific_Multi
```
the .sl script processes two inputs.
```
13 REL_NAME=${1:?REL_NAME argument missing}
14 SIMULATION_ROOT=${2:?SIMULATION_ROOT argument missing}
15 
16 FAULT=$(echo …
```
=> Fix fault/event name extraction in presence of many _s

workflow/automation/templates/run_emod3d.sl.template
Recent change kept e3d.par in LF directory by skipping it during "mv" operation. 
https://github.com/ucgmsim/slurm_gm_workflow/commit/c51afc89c7282a487ba7fbeec9edc5e937d88dea
While this change was tested ok and usually works fine, sometimes SLURM complains about mv with the  `!()` option (activated by `shopt -s extglob` ).  I haven't been able to work out why.
```
/var/spool/slurmd/job4209876/slurm_script: line 69: syntax error near unexpected token `('
/var/spool/slurmd/job4209876/slurm_script: line 69: `    mv /scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/Cybershake/v24p9/Runs/HikHBaymax/HikHBaymax_REL61/LF/!(e3d.par|OutBin/e3d.par) $backup_directory # leave e3d.par alone in case we need to restart this run'
```
I am not religious to the solution. In fact, the proposed …
=> Explicitly disable read_restart if restart is not intended

workflow/automation/org/kisti/install_realisation.pbs, workflow/automation/org/nesi/install_realisation.sl
We usually give 2-digit REL number, REL01, .... REL99.
@sarahjaneneill wants to test 100 realisations and we have a rel name with 3-digit number like `3373091_REL100`
Unfortunately, 
`FAULT=$(echo ${REL_NAME/_REL??/})`
We get a FAULT name 3373091**0** (notice the extra 0), and the wrong FAULT leads to the install_realisation step test fail for _REL100 and higher.
=> Support _REL100: Previously maximum was _REL99

workflow/automation/org/kisti/vm_gen.pbs, workflow/automation/org/nesi/vm_gen.sl
During vm_gen step, the .sl/.pbs scripts already know where SRF is, but it is not utilized to call validate_vm.py, and as a result, we don't check against the fault geometry. 
This PR fixes the problem.
=> Utilize SRF to call validate_vm.py

workflow/automation/execution_scripts/cybershake_progress.py, workflow/automation/install_scripts/create_mgmt_db.py, workflow/automation/org/nesi/vm_pert.sl, workflow/calculation/verification/check_emod3d_subdomains.py
This commit (https://github.com/ucgmsim/slurm_gm_workflow/commit/ad9e688029453b8fbf81fe414669798aabc81e2a) was introduced to update sim_params.yaml upon a successful VM perturbation step. 
However, there is no such function load() and it has always failed. In the SLURM .err log. we have
```
File "<string>", line 1, in <module>
AttributeError: module 'qcore.utils' has no attribute 'load'
```
This error was not explicitly reported, and vm_pert step is marked as "completed".
As a result, emod3d is unaware of the presence of VM perturbation file and calculates without it.
=> Correctly update sim_params.yaml if vm_pert is successful
